# Uncomment the next line to define a global platform for your project
# platform :ios, '16.6'
deployment_target = '16.6'

target 'iosApp' do
  use_frameworks!
  platform :ios, deployment_target
  # Pods for iosApp
  pod 'composeApp', :path => '../composeApp'

  # If you want to debug Bugsee XCF, then create local Bugsee pod, and add below pod module description
  # pod 'Bugsee', :path => '/Users/dsheikherev/WorkDir/Cocoapods/Local/Bugsee'
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
            end
        end
        project.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
        end
    end
end
