[versions]
agp = "8.6.0"
kotlin = "2.2.21"
bugsee-ios = "6.1.3"
bugsee-android = "7.3.0"
android-minSdk = "24"
android-compileSdk = "35"
android-targetSdk = "35"
coroutines = "1.3.0"
ktor3 = "3.2.3"
compose-multiplatform = "1.9.3"
androidx-activity = "1.10.1"
androidx-fragment = "1.8.5"
androidx-test = "1.5.0"
robolectric = "4.12.1"
junit = "4.13.2"
mockito = "5.8.0"
buildKonfig = "0.18.0"
bugseeGradle = "4.0.7"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
bugsee-android = { module = "com.bugsee:bugsee-android", version.ref = "bugsee-android" }

# Kotlin Libraries
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
ktor3-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor3" }
ktor3-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor3" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "androidx-fragment" }

# Testing Libraries
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
junit = { module = "junit:junit", version.ref = "junit" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version = "5.3.1" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.29.0" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
buildKonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }
bugsee-gradle-plugin = { id = "com.bugsee.android.gradle", version.ref = "bugseeGradle" }